apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: sourabhbhoyar/infraedgerepo:latest   # change to your Docker Hub repo & tag
        ports:
        - containerPort: 8080                   # change if your app listens on another port
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80            # external port (users will hit this)
    targetPort: 8080    # internal container port (must match containerPort above)
